---
- name: Create pod.yaml from template
  hosts: auctane
  tasks:
    - name: Generate pod.yaml from template
      ansible.builtin.template:
        src: pod_template.yaml.j2
        dest: /home/ubuntu/pod.yaml
